---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipeline-bad-format-gh-pfrm"
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  pipelineRef:
