---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: another-pr-pac-demo
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: ubuntu
              command: ["/bin/echo", "{{ trigger_comment }}"]
